#!/usr/bin/env bash

CONTAINER_NAME="anythingllm"

# Check if a container with this name is already running
if [ -n "$(docker ps | grep $CONTAINER_NAME)" ]; then
  echo "AnythingLLM is already running."
  exit 0
fi

echo "Starting AnythingLLM..."
export STORAGE_LOCATION=$HOME/anythingllm
docker run -d -p 3001:3001 \
    --cap-add SYS_ADMIN \
    -v ${STORAGE_LOCATION}:/app/server/storage \
    -v ${STORAGE_LOCATION}/.env:/app/server/.env \
    -e STORAGE_DIR="/app/server/storage" \
    mintplexlabs/anythingllm
