#!/usr/bin/python3
import sys
import json

helpMessage = """
checkjson checks if the specified key and value exists in the nested json

usage:
    checkjson <key:value> <json>

example:
    checkjson 'type:car' '{"name": "yamada", "type": "car"}'
    outputs true
"""



def check(key, value, data):

    for k, v in data.items():
        if type(v) is dict:
            if check(key, value, v):
                return True
            else:
                continue
        else:
            if key == k and value == v:
                return True



if sys.argv[1] == "-h" or sys.argv[1] == "--help":
    print(helpMessage)

else:
    [key, value] = sys.argv[1].split(":")
    data = json.loads(sys.argv[2])

    if check(key, value, data):
        print("true", end="")
    else:
        print("false", end="")

