#!/bin/bash

[ "$#" -eq 3 ] || { echo "usage: $0 <expand|shrink> <north|east|west|south> <size>"; exit 1; }

motion="$1"
direction="$2"
size="$3"

current_floating=$(bspc query -N -n .floating.focused)

[[ -z $current_floating ]] && { echo "not a floating window"; exit 1; }

if [ "$motion" = 'expand' ]; then
	# These expand the window's given side
	case "$direction" in
		north) bspc node -z top 0 -"$size" ;;
		east) bspc node -z right "$size" 0 ;;
		south) bspc node -z bottom 0 "$size" ;;
		west) bspc node -z left -"$size" 0 ;;
	esac
elif [ "$motion" = 'shrink' ]; then
	# These contract the window's given side
	case "$direction" in
		north) bspc node -z top 0 "$size" ;;
		east) bspc node -z right -"$size" 0 ;;
		south) bspc node -z bottom 0 -"$size" ;;
		west) bspc node -z left "$size" 0 ;;
	esac
fi
