#!/bin/bash

### PROCESS
# mnemonic: [K]ill [P]rocess
# show output of "ps -ef", use [tab] to select one or multiple entries
# press [enter] to kill selected processes and go back to the process list.
# or press [escape] to go back to the process list. Press [escape] twice to exit completely.

# default to sigterm -15
SIGCODE=-${1:-15}

pid=$(ps -ef \
	| sed 1d \
	| eval "fzf ${FZF_DEFAULT_OPTS} -m --header='[kill:process:$SIGCODE]'" \
	| awk '{print $2}')

if [[ -n $pid ]]; then
  echo $pid | xargs kill $SIGCODE
  $0
fi

