#!/bin/bash

# substitute whitespace with underscore and rename the file
for i in "$@"; do
	FILENAME=$(echo "$i" | tr -s ' ' | sed 's/ /_/g' | sed 's|/||g')
	echo "$FILENAME"
	[[ $i != $FILENAME ]] && mv "$i" "$FILENAME"
done

