#!/bin/bash

# default variables
ZADIR=~/.local/share/zaread/
READER="zathura"


# if ~/.zaread doesn't exist, we create it.
[[ ! -d "$ZADIR" ]] && mkdir -p "$ZADIR"cksum

# if no arguments exit.
[[ ${#@} -eq 0 ]] && exit 1


for i in "$@"; do

	file=$(basename "$i")

	# if file type is pdf, then just read the file
	if [[ $(file --mime-type "$file" | awk -F':' '{print $2}') =~ pdf$  ]]; then
	  echo "The file is already in PDF format."
	  $READER --fork "$file"
	# else check if you already have its pdf version (if not, create it)
	else
	  pdffile=${file%.*}".pdf"
	  check=$(cksum "$file" | awk '{print $1}')
	  # if pdf version hasn't ever been created, or it changed, then
	  # make conversion and store the checksum.
	  if [[ ( ! -f "$ZADIR$pdffile" ) || ( ! "$check" == $(cat "$ZADIR"cksum/"$file".check) ) ]]; then

		libreoffice --convert-to pdf "$file" --headless --outdir "$ZADIR"

		echo "$check" > "$ZADIR"cksum/"$file".check
	  fi
	  $READER --fork "$ZADIR$pdffile"
	fi
done

